dist: focal

language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-ubuntu:latest bash

script:
  - sudo apt update && sudo apt install -y  pv libxml2-dev
  - docker system prune -af
  - make pull-image
  - make -j8

notifications:
  email: false
