version: 2.1

commands:

workflows:
  version: 2

  build-push-deploy:
    jobs:
      - make

jobs:
  make:
    parallelism: 1
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt install -y pv ca-certificates apt-transport-https
      - run: sudo apt-get install --reinstall ca-certificates
      - run: sudo update-ca-certificates
      - run: docker system prune -af
      - run: make pull-image
      - run: make -j1

